name: scanit
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_gallery_saver_plus: ^4.0.1

  permission_handler: ^11.3.1 # versi stabil per Juni 2025
  screenshot: ^3.0.0
  mobile_scanner: ^3.5.1
  path_provider: ^2.1.2
  flutter_svg: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/qr_illustration.svg
